module.exports = {
  DB_COLLECTION_NAME: "players",
  INVALID_TEAM_SIZE: "INVALID_TEAM_SIZE",
  INVALID_PLAYER: "INVALID_PLAYER",
  INVALID_TEAM_CONFIG: "INVALID_TEAM_CONFIG",
  INVALID_TEAM_NAME: "INVALID_TEAM_NAME",
};
